### ISSUE TITLE
git lfs pull error

### ISSUE THREAD

**Issue by Xiezhaotong** [Fg21Sim/fg21sim#2]
Hi,

I found the problem that data cannot be `git lfs pull`. It returned:

`Error downloading object: data/Halpha_fwhm06_ns1024.fits.xz (85b9d1f): Smudge error: Error downloading data/Halpha_fwhm06_ns1024.fits.xz (85b9d1ffe75ca87ae2a8c0bf8d674a95d92b6bbff68caa301164aa46848f5984): [85b9d1ffe75ca87ae2a8c0bf8d674a95d92b6bbff68caa301164aa46848f5984] Object does not exist on the server: [404] Object does not exist on the server`.

**Comment by ChenxiSSS** [comment]
Hi, we have offered an alternative data download method. You can find the info via https://github.com/Fg21Sim/Data/blob/main/README.md.

Best,
Chenxi

**Comment by Xiezhaotong** [comment]
Thanks a million. I really appreciate it.
